site_name: AWS Security Services Best Practices
repo_name: aws/aws-security-services-best-practices
repo_url: https://github.com/aws/aws-security-services-best-practices
docs_dir: 'docs/en'
copyright: 'Copyright &copy; Amazon 2023'
site_author: 'AWS'
site_url: 'https://aws.github.io/aws-security-services-best-practices'
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - tabs
    - content.code.copy
    - announce.dismiss
    - header.autohide
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: switch to light mode

nav:
  - Home: index.md
  - Amazon Detective Best Practices: guides/detective/index.md
  - Amazon GuardDuty Best Practices: guardduty/index.md
  - Amazon Inspector Best Practices: inspector-best-practices/index.md
  - Amazon Macie Best Practices: macie/index.md
  - AWS Security Hub Best Practices: security-hub/index.md
  - Contributors: contributors.md
plugins:
    - search
